export enum Actions {
  ADD_TASK = 'ADD_TASK',
  DELETE_TASK = 'DELETE_TASK',
  ADD_POMODORO = 'ADD_POMODORO',
  DELETE_POMODORO = 'DELETE_POMODORO',
  ADD_MINUTE = 'ADD_MINUTE',
  DELETE_MINUTE = 'DELETE_MINUTE',
  EDIT_TASK = 'EDIT_TASK',
}